name: CI/CD 

on:
  push:
    branches:
      - main

jobs:

  web-deploy:
    name: Auto Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync Files
        uses: Burnett01/rsync-deployments@6.0.0
        with:
        # The switches
          switches: -avzr --delete --exclude=".git" --exclude=".github" --exclude=".gitignore"
          path: /
          # The remote path
          remote_path: ${{ secrets.DEPLOY_PATH }}
          # The remote host
          remote_host: ${{ secrets.DEPLOY_HOST }}
          # The remote user
          remote_user: ${{ secrets.DEPLOY_USER }}
          # The remote key
          remote_key: ${{ secrets.DEPLOY_KEY }}
