name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Auto Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Sync Files
        uses: Burnett01/rsync-deployments@6.0.0
        with:
          # The switches
          switches: -avzr --delete --exclude=".git" --exclude=".github" --exclude=".gitignore" --exclude="uploads"
          path: /
          # The remote path
          remote_path: /home/u1566631/public_html/test/
          # The remote host
          remote_host: ${{ secrets.DEPLOY_HOST }}
          # The remote user
          remote_user: ${{ secrets.DEPLOY_USER }}
          # The remote key
          remote_key: ${{ secrets.DEPLOY_KEY }}

      - name: Run tests
        run: npm test

      - name: Start Server
        run: node index.js
